name: Publish Docker Image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build App
        run: chmod +x gradlew && ./gradlew assembleDist
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_PACKAGES }}
          registry: docker.pkg.github.com
          repository: telestionteam/rocketsound/telestion-rocketsound
          tag_with_sha: true
